// Built-in caption style presets ("themes") for CaptionsModal's theme
// picker. Each theme groups a full subtitle style (font, size, colors,
// position, animation...) under one catchy name so a user can get a
// finished look in one click instead of tuning every option by hand.
// Purely static, frontend-only data -- a user's own saved/customized
// themes are fetched separately from GET /api/caption-style-themes (see
// app.py's caption_style_themes endpoints) and never live here.

export const BUILTIN_CAPTION_THEMES = [
  {
    id: 'punch-viral',
    name: 'Punch Viral',
    emoji: '🔥',
    style: {
      positionX: 50, positionY: 82,
      fontFamily: 'Bebas Neue', fontSize: 64,
      fontColor: '#FFFFFF', highlightColor: '#FFDD00',
      borderColor: '#000000', borderWidth: 4,
      textShadowColor: '#000000', shadowBlur: 10, shadowOffsetX: 0, shadowOffsetY: 3,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'karaoke',
    },
  },
  {
    id: 'neon-city',
    name: 'Néon City',
    emoji: '⚡',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Orbitron', fontSize: 50,
      fontColor: '#00F0FF', highlightColor: '#FF2FD0',
      borderColor: '#0A0033', borderWidth: 2,
      textShadowColor: '#00F0FF', shadowBlur: 18, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0.35,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 4, animation: 'word-highlight',
    },
  },
  {
    id: 'epure',
    name: 'Épuré',
    emoji: '⚪',
    style: {
      positionX: 50, positionY: 84,
      fontFamily: 'Inter', fontSize: 44,
      fontColor: '#FFFFFF', highlightColor: '#FFFFFF',
      borderColor: '#000000', borderWidth: 0,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 5, animation: 'fade-in-out',
    },
  },
  {
    id: 'conte-du-soir',
    name: 'Conte du Soir',
    emoji: '📖',
    style: {
      positionX: 50, positionY: 50,
      fontFamily: 'Caveat', fontSize: 60,
      fontColor: '#FFF6E5', highlightColor: '#FF9AC1',
      borderColor: '#3A2A1A', borderWidth: 2,
      textShadowColor: '#000000', shadowBlur: 10, shadowOffsetX: 0, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 4, animation: 'fade-in-out',
    },
  },
  {
    id: 'comedie-club',
    name: 'Comédie Club',
    emoji: '😂',
    style: {
      positionX: 50, positionY: 78,
      fontFamily: 'Bangers', fontSize: 58,
      fontColor: '#FFD400', highlightColor: '#FF5A5F',
      borderColor: '#1A1A1A', borderWidth: 3,
      textShadowColor: '#000000', shadowBlur: 8, shadowOffsetX: 2, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'pop',
    },
  },
  {
    id: 'pro-business',
    name: 'Pro Business',
    emoji: '💼',
    style: {
      positionX: 50, positionY: 85,
      fontFamily: 'Poppins', fontSize: 42,
      fontColor: '#FFFFFF', highlightColor: '#3B82F6',
      borderColor: '#000000', borderWidth: 0,
      textShadowColor: '#000000', shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#0B1220', bgOpacity: 0.65,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 6, animation: 'none',
    },
  },
  {
    id: 'retro-pop',
    name: 'Rétro Pop',
    emoji: '🎞️',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Righteous', fontSize: 54,
      fontColor: '#FFFFFF', highlightColor: '#FF6B35',
      borderColor: '#7A0C2E', borderWidth: 4,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 3, shadowOffsetY: 3,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 4, animation: 'zoom-in-out',
    },
  },
  {
    id: 'karaoke-party',
    name: 'Karaoké Party',
    emoji: '🎤',
    style: {
      positionX: 50, positionY: 82,
      fontFamily: 'Luckiest Guy', fontSize: 52,
      fontColor: '#FFFFFF', highlightColor: '#FFDD00',
      borderColor: '#4B0082', borderWidth: 3,
      textShadowColor: '#000000', shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2,
      bgColor: '#1A0B2E', bgOpacity: 0.5,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 4, animation: 'karaoke',
    },
  },
  {
    id: 'elegance-doree',
    name: 'Élégance Dorée',
    emoji: '✨',
    style: {
      positionX: 50, positionY: 86,
      fontFamily: 'Playfair Display', fontSize: 46,
      fontColor: '#F5E6C8', highlightColor: '#D4AF37',
      borderColor: '#000000', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: true,
      wordsPerLine: 5, animation: 'slide-in-out',
    },
  },
  {
    id: 'cine-classique',
    name: 'Ciné Classique',
    emoji: '🎬',
    style: {
      positionX: 50, positionY: 88,
      fontFamily: 'Trebuchet MS', fontSize: 40,
      fontColor: '#FFFFFF', highlightColor: '#FFFFFF',
      borderColor: '#000000', borderWidth: 2,
      textShadowColor: '#000000', shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 6, animation: 'none',
    },
  },
  {
    id: 'choc-titres',
    name: 'Choc Titres',
    emoji: '📰',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Impact', fontSize: 58,
      fontColor: '#FFFFFF', highlightColor: '#FFDD00',
      borderColor: '#000000', borderWidth: 3,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 2, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0.55,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'pop',
    },
  },
  {
    id: 'vague-pastel',
    name: 'Vague Pastel',
    emoji: '🌊',
    style: {
      positionX: 50, positionY: 84,
      fontFamily: 'Comfortaa', fontSize: 42,
      fontColor: '#FFE3EC', highlightColor: '#B5E6E0',
      borderColor: '#5C4B66', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 5, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 5, animation: 'fade-in-out',
    },
  },
  {
    id: 'rage-mode',
    name: 'Rage Mode',
    emoji: '😡',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Anton', fontSize: 56,
      fontColor: '#FFFFFF', highlightColor: '#FF1E1E',
      borderColor: '#1A0000', borderWidth: 4,
      textShadowColor: '#FF1E1E', shadowBlur: 10, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'active-color',
    },
  },
  {
    id: 'sunset-vibes',
    name: 'Sunset Vibes',
    emoji: '🌅',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Fredoka', fontSize: 50,
      fontColor: '#FFF3E0', highlightColor: '#FF7A59',
      borderColor: '#7A2E00', borderWidth: 2,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 4, animation: 'zoom-in-out',
    },
  },
  {
    id: 'machine-a-ecrire',
    name: 'Machine à Écrire',
    emoji: '⌨️',
    style: {
      positionX: 50, positionY: 86,
      fontFamily: 'Courier New', fontSize: 38,
      fontColor: '#F5F5F0', highlightColor: '#F5F5F0',
      borderColor: '#000000', borderWidth: 0,
      textShadowColor: '#000000', shadowBlur: 3, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#1A1A1A', bgOpacity: 0.7,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 6, animation: 'none',
    },
  },
  {
    id: 'glitch-tech',
    name: 'Glitch Tech',
    emoji: '🛸',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Audiowide', fontSize: 44,
      fontColor: '#C6FF00', highlightColor: '#B026FF',
      borderColor: '#120021', borderWidth: 2,
      textShadowColor: '#B026FF', shadowBlur: 14, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0.3,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 4, animation: 'rotate-in-out',
    },
  },
  {
    id: 'bubblegum-fun',
    name: 'Bubblegum Fun',
    emoji: '🍬',
    style: {
      positionX: 50, positionY: 78,
      fontFamily: 'Bubblegum Sans', fontSize: 52,
      fontColor: '#FF6FB5', highlightColor: '#FFE45E',
      borderColor: '#FFFFFF', borderWidth: 3,
      textShadowColor: '#7A1F5C', shadowBlur: 6, shadowOffsetX: 2, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 4, animation: 'pop',
    },
  },
  {
    id: 'presse-choc',
    name: 'Presse Choc',
    emoji: '🚨',
    style: {
      positionX: 50, positionY: 84,
      fontFamily: 'Rubik Mono One', fontSize: 40,
      fontColor: '#FFDD00', highlightColor: '#FFFFFF',
      borderColor: '#000000', borderWidth: 0,
      textShadowColor: '#000000', shadowBlur: 2, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#B00000', bgOpacity: 0.85,
      textCase: 'uppercase', bold: false, italic: false,
      wordsPerLine: 4, animation: 'slide-in-out',
    },
  },
  {
    id: 'douceur-manuscrite',
    name: 'Douceur Manuscrite',
    emoji: '🖋️',
    style: {
      positionX: 50, positionY: 84,
      fontFamily: 'Patrick Hand', fontSize: 50,
      fontColor: '#FFF7E8', highlightColor: '#F2B880',
      borderColor: '#4A2E12', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 5, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 5, animation: 'emoticon',
    },
  },
  {
    id: 'arcade-retro',
    name: 'Arcade Rétro',
    emoji: '👾',
    style: {
      positionX: 50, positionY: 82,
      fontFamily: 'Press Start 2P', fontSize: 28,
      fontColor: '#39FF14', highlightColor: '#FFFFFF',
      borderColor: '#000000', borderWidth: 2,
      textShadowColor: '#39FF14', shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0.6,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 3, animation: 'word-highlight',
    },
  },
  {
    id: 'mrbeast-mode',
    name: 'MrBeast Mode',
    emoji: '🤑',
    style: {
      positionX: 50, positionY: 78,
      fontFamily: 'Lilita One', fontSize: 62,
      fontColor: '#FFE600', highlightColor: '#FF3B30',
      borderColor: '#000000', borderWidth: 5,
      textShadowColor: '#000000', shadowBlur: 4, shadowOffsetX: 2, shadowOffsetY: 2,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'pop',
    },
  },
  {
    id: 'gold-luxe',
    name: 'Gold Luxe',
    emoji: '👑',
    style: {
      positionX: 50, positionY: 85,
      fontFamily: 'Cinzel', fontSize: 46,
      fontColor: '#F4E3B2', highlightColor: '#D4AF37',
      borderColor: '#000000', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 5, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0.4,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 5, animation: 'fade-in-out',
    },
  },
  {
    id: 'esport-arena',
    name: 'Esport Arena',
    emoji: '🎮',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Kanit', fontSize: 54,
      fontColor: '#39FF88', highlightColor: '#FF2E63',
      borderColor: '#05010F', borderWidth: 3,
      textShadowColor: '#39FF88', shadowBlur: 14, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: true, italic: false,
      wordsPerLine: 3, animation: 'zoom-in-out',
    },
  },
  {
    id: 'street-graffiti',
    name: 'Street Graffiti',
    emoji: '🧢',
    style: {
      positionX: 50, positionY: 80,
      fontFamily: 'Bungee', fontSize: 50,
      fontColor: '#FFFFFF', highlightColor: '#FFB800',
      borderColor: '#000000', borderWidth: 4,
      textShadowColor: '#000000', shadowBlur: 4, shadowOffsetX: 3, shadowOffsetY: 3,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'uppercase', bold: false, italic: false,
      wordsPerLine: 3, animation: 'rotate-in-out',
    },
  },
  {
    id: 'kpop-glam',
    name: 'K-Pop Glam',
    emoji: '💖',
    style: {
      positionX: 50, positionY: 82,
      fontFamily: 'Baloo 2', fontSize: 48,
      fontColor: '#FFD1E8', highlightColor: '#B388FF',
      borderColor: '#5A2A6B', borderWidth: 2,
      textShadowColor: '#000000', shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 4, animation: 'word-highlight',
    },
  },
  {
    id: 'asmr-whisper',
    name: 'ASMR Whisper',
    emoji: '🎧',
    style: {
      positionX: 50, positionY: 50,
      fontFamily: 'Kalam', fontSize: 40,
      fontColor: '#FDEEF4', highlightColor: '#FFC1D9',
      borderColor: '#4A2E3B', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: true,
      wordsPerLine: 5, animation: 'fade-in-out',
    },
  },
  {
    id: 'horreur-creepy',
    name: 'Horreur Creepy',
    emoji: '🕷️',
    style: {
      positionX: 50, positionY: 78,
      fontFamily: 'Creepster', fontSize: 52,
      fontColor: '#D6FFB3', highlightColor: '#8B0000',
      borderColor: '#000000', borderWidth: 3,
      textShadowColor: '#4B0082', shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 0,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 3, animation: 'active-color',
    },
  },
  {
    id: 'vlog-casual',
    name: 'Vlog Casual',
    emoji: '📱',
    style: {
      positionX: 50, positionY: 86,
      fontFamily: 'Nunito', fontSize: 40,
      fontColor: '#FFFFFF', highlightColor: '#4ADE80',
      borderColor: '#000000', borderWidth: 2,
      textShadowColor: '#000000', shadowBlur: 3, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0.35,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 6, animation: 'none',
    },
  },
  {
    id: 'love-mode',
    name: 'Love Mode',
    emoji: '💘',
    style: {
      positionX: 50, positionY: 84,
      fontFamily: 'Pacifico', fontSize: 46,
      fontColor: '#FFE4EC', highlightColor: '#FF4D6D',
      borderColor: '#7A1F3D', borderWidth: 1,
      textShadowColor: '#000000', shadowBlur: 5, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#000000', bgOpacity: 0,
      textCase: 'none', bold: false, italic: false,
      wordsPerLine: 4, animation: 'zoom-in-out',
    },
  },
  {
    id: 'podcast-clean',
    name: 'Podcast Clean',
    emoji: '🎙️',
    style: {
      positionX: 50, positionY: 88,
      fontFamily: 'Montserrat', fontSize: 38,
      fontColor: '#FFFFFF', highlightColor: '#38BDF8',
      borderColor: '#000000', borderWidth: 0,
      textShadowColor: '#000000', shadowBlur: 2, shadowOffsetX: 0, shadowOffsetY: 1,
      bgColor: '#111827', bgOpacity: 0.7,
      textCase: 'none', bold: true, italic: false,
      wordsPerLine: 7, animation: 'none',
    },
  },
];

export const findBuiltinCaptionTheme = (id) => BUILTIN_CAPTION_THEMES.find((theme) => theme.id === id) || null;
