import {
    Clapperboard,
    Home,
    LayoutGrid,
    MessageSquareText,
    Quote,
    Share2,
} from "lucide-react";

export const DASHBOARD_SIDEBAR_ITEMS = [
    {
        key: "dashboard",
        title: "Dashboard",
        sidebarLabel: "Dashboard",
        icon: Home,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Hub principal pour acceder a tous les outils Vireel et a ton espace de production.",
        badge: "Hub",
        category: "hub",
        path: "/dashboard",
    },
    {
        key: "reels",
        title: "Réels",
        sidebarLabel: "Réels",
        icon: LayoutGrid,
        activeClassName: "bg-violet-500/10 text-violet-400",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Upload une vidéo et laisse le système boosté à l'IA extraire les moments réels.",
        badge: "Projets",
        category: "service",
        path: "/dashboard/reels",
    },
    {
        key: "captions",
        title: "Sous-titres",
        sidebarLabel: "Sous-titres",
        icon: MessageSquareText,
        activeClassName: "bg-yellow-500/10 text-yellow-400",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Genere et gere des sous-titres de maniere autonome pour tes videos locales.",
        badge: "Projets",
        category: "service",
        path: "/dashboard/captions",
    },
    {
        key: "anonymous-stories",
        title: "Histoires anonymes",
        sidebarLabel: "Histoires anonymes",
        icon: Quote,
        activeClassName: "bg-pink-500/10 text-pink-400",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Transforme une video temoignage en histoire ecrite anonymisee, prete a copier.",
        badge: "Projets",
        category: "service",
        path: "/dashboard/anonymous-stories",
    },
    {
        key: "film-summaries",
        title: "Résumé de film",
        sidebarLabel: "Résumé de films",
        icon: Clapperboard,
        activeClassName: "bg-teal-500/10 text-teal-400",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Transforme un film complet en résumé monté et narré, prêt à revoir avant génération.",
        badge: "Projets",
        category: "service",
        path: "/dashboard/film-summaries",
    },
    {
        key: "social-publications",
        title: "Publications sociales",
        sidebarLabel: "Publications",
        icon: Share2,
        activeClassName: "bg-green-500/10 text-green-400",
        inactiveClassName: "text-slate-500 dark:text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Suivi en temps réel de vos publications sur les réseaux sociaux.",
        badge: "Monitoring",
        category: "service",
        path: "/dashboard/social-publications",
    },
];